name: Deploy to GitHub Pages (branch folders)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to GitHub Pages (main branch)
      if: github.ref_name == 'main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: src
        clean: false

    - name: Deploy to GitHub Pages (branch subdirectory)
      if: github.ref_name != 'main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: src
        branch: main
        target-folder: ${{ github.ref_name }}
        clean: false
